### PR TITLE
Reg dev

### PR DESCRIPTION
**Pull request by samuelokellogum**
## Description
Added a registration endpoint

## How Has This Been Tested?
Tested using postman with tests passing

### CODE REVIEW

**Review by Nataanthoni — COMMENTED** [review]
Hi @samuelokellogum, Nice work there. I just have a few concerns, please do look into this and try fixing or give you advice;

- Why are you validating from another function. For simplicity, scalability and better organization of code, can you consider doing this from the same function. 
- According to the previous meeting, the front end guys expect a business type fiend. When are you going to do this?
- 'User Successfully Registered' may need to be changed to Registration successful or something close to that since, in this case, we are thinking a user will register him/herself instead of the previous approach. This is definitely not a very important concern.
- In your validator function, businessName is not required yet notnullable from the db schema. Can you please revise this?
- Lastly, whan all this is done, please try to give a simple API documentation to guide the front end guys.
Everything else looks fine.

Thanks.

**Comment by samuelokellogum** [comment]
Hi Anthony,
All have been fixed however, could you send me a link to the API document. So I can document it there. Thanks.

**Review by Nataanthoni — APPROVED** [review]
All good.

**Comment by Nataanthoni** [comment]
Hey,

Thanks is for the great work then.

Unfortunately, the documentations is unsharedble as it's auto generated
2hen you import or create postmans collections and published. You could try
sharing with me an let me put it up or better still, you could import
postman collections and make changes.


Also, I'm going to try sharing with you the collection.

**Comment by samuelokellogum** [comment]
Whats your email address?

**Pull request merged**
